services:
  phpdoc:
    build:
      dockerfile: .docker/Dockerfile
    container_name: phpdoc-builder
    working_dir: /var/www
    user: "0:0"
    volumes:
      - ../doc-${LANGUAGE:-en}:/var/www/${LANGUAGE:-en}
      - ../doc-en:/var/www/en
      - ../doc-base:/var/www/doc-base
    command: ["${LANGUAGE:-en}", "xhtml"]

  phpdoc-web:
    image: php:8.2-cli-alpine
    container_name: phpdoc-web
    working_dir: /var/www/${LANGUAGE:-en}/output
    volumes:
      - ../doc-${LANGUAGE:-en}/output/php-chunked-xhtml:/var/www/${LANGUAGE:-en}/output
    ports:
      - "8000:8000"
    command: ["php", "-S", "0.0.0.0:8000", "-t", "/var/www/${LANGUAGE:-en}/output"]
