services:
  phpdoc:
    build:
      dockerfile: .docker/Dockerfile
    container_name: phpdoc-builder
    working_dir: /var/www
    user: "0:0"
    volumes:
      - ../doc-fr:/var/www/fr
      - ../doc-en:/var/www/en
      - ../doc-base:/var/www/doc-base
    command: ["fr", "xhtml"]

  phpdoc-web:
    image: php:8.2-cli-alpine
    container_name: phpdoc-web
    working_dir: /var/www/fr/output
    volumes:
      - ../doc-fr/output/php-chunked-xhtml:/var/www/fr/output
    ports:
      - "8000:8000"
    command: ["php", "-S", "0.0.0.0:8000", "-t", "/var/www/fr/output"]
