#!/bin/sh
# $Id$

for i in `find $1 -name "*.[ch]" -print -o -name "*.ec" -print | xargs egrep -li "{{{ proto"` ; do
echo $i | sed -e 's/\.\.\//# /'
awk -f funcsummary.awk < $i | sort +1 | awk -F "---" '{ print $1; print $2; }' | sed 's/^[[:space:]]+//'
done
if test -f $1/language-scanner.lex # only in PHP3
then
awk -f funcsummary.awk < $1/language-scanner.lex | sort +1 | awk -F "---" '{ print $1; print $2; }'
fi
 