<?php 
/*
# 
# +----------------------------------------------------------------------+
# | PHP Manual                                                           |
# +----------------------------------------------------------------------+
# | Copyright (c) 2001 PHP Documentation Team                            |
# +----------------------------------------------------------------------+
# | This program is free software; you can redistribute it and/or modify |
# | it under the terms of the GNU General Public License as published by |
# | the Free Software Foundation; either version 2 of the License, or    |
# | (at your option) any later version.                                  |
# |                                                                      |
# | This program is distributed in the hope that it will be useful,      |
# | but WITHOUT ANY WARRANTY; without even the implied warranty of       |
# | MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the        |
# | GNU General Public License for more details.                         |
# |                                                                      |
# | You should have received a copy of the license refered to here in a  |
# | file called LICENSE. If you did not, or have any questions about PHP |
# | licensing, please contact hartmut@six.de.                            |
# +----------------------------------------------------------------------+
# | Authors:    Hartmut Holzgraefe <hartmut@six.de>                      |
# +----------------------------------------------------------------------+
# 
# $Id$
*/
echo "<?xml version=\"1.0\" encoding=\"$argv[2]\" ?>\n";
echo "<!-- do not edit this file, it was auto genereated $argv[0] -->\n";
?>
 <index id="index.functions">
  <title>&FunctionIndex;</title>
<?php
$letter=" ";
$functions = file($argv[1]);
usort($functions,"strcasecmp");
foreach ( $functions as $funcentry ) {
	list($function,$description) = explode("-",$funcentry);
	$function=strtolower(trim($function));
	if(!ereg("^[[:alnum:]]",$function)) continue;
	if($function{0}!=$letter) {
		if($letter!=" ") {
			echo "  </indexdiv>\n";
		}
		$letter=$function{0};
		echo "  <indexdiv>\n";
		echo "   <title>".strtoupper($letter)."</title>\n";
	}
	echo "   <indexentry><primaryie><function>$function</function></primaryie></indexentry>\n";
}
?>
  </indexdiv>
 </index>
