#!/bin/sh
# 
# +----------------------------------------------------------------------+
# | PHP HTML Embedded Scripting Language                                 |
# +----------------------------------------------------------------------+
# | Copyright (c) 1997 - 2001 PHP Development Team (See Credits file)    |
# +----------------------------------------------------------------------+
# | This program is free software; you can redistribute it and/or modify |
# | it under the terms of one of the following licenses:                 |
# |                                                                      |
# | A) the GNU General Public License as published by the Free Software  |
# | Foundation; either version 2 of the License, or (at your option)     |
# | any later version.                                                   |
# |                                                                      |
# | B) the PHP License as published by the PHP Development Team and      |
# | included in the distribution in the file: LICENSE                    |
# |                                                                      |
# | This program is distributed in the hope that it will be useful,      |
# | but WITHOUT ANY WARRANTY; without even the implied warranty of       |
# | MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the         |
# | GNU General Public License for more details.                         |
# |                                                                      |
# | You should have received a copy of both licenses referred to here.   |
# | If you did not, or have any questions about PHP licensing, please    |
# | contact core@php.net.                                                |
# +----------------------------------------------------------------------+
# | Authors: Ariel Shkedi <ars@ziplink.net> or <as@altavista.net>        |
# | Rasmus Lerdorf <rasmus@lerdorf.on.ca>                                |
# +----------------------------------------------------------------------+
# 
# $Id$

for i in `find $1 -name "*.[c]" -print -o -name "*.ec" -print | xargs egrep -li function_entry` ; do
echo $i | sed -e 's/\.\.\//# /'
awk -f funcparse.awk < $i | sort
done
if test -f $1/language-scanner.lex # only in PHP3 sources
then 
echo $1/language-scanner.lex | sed -e 's/\.\.\//# /'
awk -f funcparse.awk < $1/language-scanner.lex | sort
fi 
