#!/bin/sh
# $Id$

for i in `find .. -name "*.[ch]" -print -o -name "*.ec" -print | xargs egrep -li "{{{ proto" ` ; do
 echo $i | sed -e 's/\.\.\//# /'
 awk -f funcsummary.awk < $i | sort +1 | awk -F "---" '{ print $1; print $2; }' | sed 's/^[[:space:]]+//'
done
awk -f funcsummary.awk < ../language-scanner.lex | sort +1 | awk -F "---" '{ print $1; print $2; }'
