#!/bin/bash
# taken from cvs.php.net/functable by Harmut


if [ ! -d sources ] 
then
	mkdir sources
fi

cd sources

# getting php4 releases
for release in `xargs echo < ../version4.tags`
 do
  if [ ! -d $release ]
   then 
    echo fetching $release from cvs
    ../cvs-get-release php-src $release
  else
    echo $release already there
  fi
done

# getting php4 latest developement snapshot
echo updating php4 cvs
if [ -d php_4_cvs ]
 then
  (cd php_4_cvs; cvs update 2>&1 | grep -v "^. php_4_cvs" | grep -v Updating)
else
  cvs -d ":pserver:cvsread@cvs.php.net:/repository" get -d php_4_cvs -r PHP_4_3 php-src
fi


# getting php5 releases
for release in `xargs echo < ../version5.tags`
 do
  if [ ! -d $release ]
   then 
    echo fetching $release from cvs
    ../cvs-get-release php-src $release
  else
    echo $release already there
  fi
done

# getting php5 latest developement snapshot
echo updating php5 cvs
if [ -d php_5_cvs ]
 then
  (cd php_5_cvs; cvs update 2>&1 | grep -v "^. php_5_cvs" | grep -v Updating)
else
  cvs -d ":pserver:cvsread@cvs.php.net:/repository" get -d php_5_cvs -r HEAD php-src
fi
