#!/bin/bash
# taken from cvs.php.net/functable by Harmut
PHP_4_CVS=PHP_4_4
PHP_5_CVS=PHP_5_1
PHP_6_CVS=HEAD


if [ ! -d sources ] 
then
	mkdir sources
fi

cd sources

# getting php4 releases
for release in `xargs echo < ../version4.tags`
 do
  if [ ! -d $release ]
   then 
    echo fetching $release from cvs
    ../cvs-get-release php-src $release
  else
    echo $release already there
  fi
done

# getting php4 latest developement snapshot
echo updating php4 cvs
cvs -q -d ":pserver:cvsread@cvs.php.net:/repository" co -d php_4_cvs -r $PHP_4_CVS php-src


# getting php5 releases
for release in `xargs echo < ../version5.tags`
 do
  if [ ! -d $release ]
   then 
    echo fetching $release from cvs
    ../cvs-get-release php-src $release
  else
    echo $release already there
  fi
done

# getting php5 latest developement snapshot
echo updating php5 cvs
cvs -q -d ":pserver:cvsread@cvs.php.net:/repository" co -d php_5_cvs -r $PHP_5_CVS php-src

# getting php6 latest developement snapshot
echo updating php6 cvs
cvs -q -d ":pserver:cvsread@cvs.php.net:/repository" co -d php_6_cvs -r $PHP_6_CVS php-src
