<?php

/* 
   This file is part of the Windows Compiled HTML Help
   Manual Generator of the PHP Documentation project.
   
   Please provide all directory values without a trailing
   backslash. Paths are relative to the "phpdoc\htmlhelp"
   directory. Be sure, not to give any directory or
   file names with spaces in them.
*/

/*
  This must be a valid language code used
  in the phpdoc repository. Defaults to en.
*/
$LANGUAGE = 'en';

/*
  This must be the path including the executable
  file's name of the hhc.exe included in Microsoft
  HTML Help Workshop. The default is
  'c:\\progra~1\\_development\\htmlhe~1\\hhc.exe'.
*/
$HELP_WORKSHOP = 'c:\\progra~1\\_development\\htmlhe~1\\hhc.exe';

/*
  This must be the directory, where the XSL 
  generated HTML files and hh[pkc] supplemental
  files can be found. The defaults is
  'html', the html output dir used by HTMLHelp
  XSL style sheets.
*/
$HTML_SRC = 'html';

/*
  This is the directory, where the files generated
  by this system should go. The default is 'htmlout'.
  
  Beware, that if you set this to the same as the above,
  the start cleanup will delete your source files (so you
  need to set $START_CLEANUP to FALSE in that case!)
*/
$HTML_TARGET = 'htmlout';

/*
  This must be a valid directory name, where
  the manual note sources can be found. The default
  is 'notesin' (a directory under "phpdoc\htmlhelp").
*/
$NOTES_SRC = 'notesin';

/*
  This is the directory name, where the HTML files
  for the notes help file go. The default is 'notesout'
  (a directory under "phpdoc\htmlhelp"). It is created
  if nonexistent.
*/
$NOTES_TARGET = 'notesout';

/*
  This is the directory name, where all the release
  files will go. The default is 'release'
  (a directory under "phpdoc\htmlhelp").
  It is created if nonexistent.
*/
$RELEASE_DIR = 'release';

/*
  This must be TRUE or FALSE, depending on
  whether you would like to use notes sources to
  build a "php_manual_notes.chm" output file
  or not. The default is to generate a note file.
  
  Note, that it is only safe to generate a notes
  file with the English version, as it has all
  the pages, while other translations don't have
  them, so using them as note bases would cause
  note data loss.
*/
$USE_NOTES = TRUE;

/*
  This must be TRUE or FALSE, depending on
  whether you would like the script to do
  automatic cleanup on startup. The script cleans
  up all working directories, except $HTML_SRC,
  where the sources of this script are.
  This means that $HTML_TARGET, $NOTES_SRC,
  $NOTES_TARGET and $RELEASE_DIR folders are
  emptyed if this is TRUE.
*/
$START_CLEANUP = TRUE;

/*
  Deletes all work files except the files in $RELEASE_DIR.
  This means that all the $HTML_SRC, $HTML_TARGET, $NOTES_SRC
  and $NOTES_TARGET directories are emptyed. You probably never
  want to do this, if you are developing the system, as all the
  HTML source files generated by "make" will be lost, and you
  need to start over again from make.
*/
$END_CLEANUP = FALSE;

?>