#!/bin/sh

cd ..
cvs -q up
autoconf
./configure --with-chm=yes --without-internals
make test
make test_xml
make chm_xsl

cd htmlhelp
rm -f mirrors.inc all

wget http://php.net/include/mirrors.inc
wget http://php.net/backend/notes/all.bz2

bunzip2 all.bz2
./make_chm.bat
cd release
zip -9 -r php_manual_chm.zip *
