name: "Bug Report"
description: "Report an issue with the PHP documentation"
labels: ["bug"]

body:
  - type: input
    id: affected-page
    attributes:
      label: "Affected page"
      description: "Provide the URL or file path of the affected documentation page."
      placeholder: "e.g., https://www.php.net/manual/en/function.strlen.php"
    validations:
      required: true

  - type: textarea
    id: issue-description
    attributes:
      label: "Issue description"
      description: "Describe the bug, including incorrect behavior, broken links, or missing content."
      placeholder: "Describe what's wrong or missing on the page."
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: "Steps to reproduce"
      description: "Explain how to reproduce the issue."
      placeholder: |
        1. Go to the page
        2. Describe the actions
        3. Explain the expected behavior
    validations:
      required: false

  - type: textarea
    id: suggested-fix
    attributes:
      label: "Suggested fix"
      description: "Provide corrections or relevant references if possible."
      placeholder: "e.g., link to correct behavior or suggested text/code."
    validations:
      required: false
