name: "Documentation Improvement"
description: "Suggest an improvement for the PHP documentation"
labels: ["enhancement"]

body:
  - type: input
    id: affected-page
    attributes:
      label: "Affected page"
      description: "Provide the URL or file path of the documentation to improve."
      placeholder: "e.g., https://www.php.net/manual/en/function.strlen.php"
    validations:
      required: true

  - type: textarea
    id: current-issue
    attributes:
      label: "Current issue"
      description: "Explain what is wrong or lacking, such as outdated info, missing examples, or unclear explanations."
      placeholder: "Explain why the current documentation needs improvement."
    validations:
      required: true

  - type: textarea
    id: suggested-improvement
    attributes:
      label: "Suggested improvement"
      description: "Provide updated content, better examples, or clarifications."
      placeholder: "Share your proposed improvement."
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: "Additional context (optional)"
      description: "Provide references, links, or examples from official or relevant sources."
      placeholder: "Optional references or further explanation."
    validations:
      required: false
