<?xml version="1.0" encoding="iso-8859-1"?>
<!-- 

  param_html.xsl: Parameters generated by the configure-script

-->
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                version="1.0">


<xsl:output method="html" encoding="ISO-8859-1"/>



</xsl:stylesheet>
