name: check-whitespace

# Get the repository with all commits to ensure that we can analyze
# all of the commits contributed via the Pull Request.
# Process `git log --check` output to extract just the check errors.
# Exit with failure upon white-space issues.

on:
  pull_request:
    types: [opened, synchronize]

permissions:
  contents: read

jobs:
  check-whitespace:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - run: |
          git config --global user.name "check-whitespace"
          git config --global user.email "check-whitespace@example.com"
      - run: git checkout ${{github.event.pull_request.base.sha}}
      - run: git merge --squash ${{github.event.pull_request.head.sha}}
      - run: git commit -m "Squashed"
      - run: git log --check HEAD^..HEAD
